# Generated by Django 5.2 on 2025-05-05 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Value of experience should not be less than 0."
                    ),
                    django.core.validators.MaxValueValidator(
                        80, message="Value of experience should not be more than 80."
                    ),
                ],
            ),
        ),
    ]
